# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.ws_push import WsPush

class TestWsPush(unittest.TestCase):
    """WsPush unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WsPush:
        """Test WsPush
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WsPush`
        """
        model = WsPush()
        if include_optional:
            return WsPush(
                channel = 'tradingAccount:acc-123',
                pub = cadenza_client.models.ws_publication.wsPublication(
                    data = { }, 
                    info = cadenza_client.models.ws_client_info.wsClientInfo(
                        user = 'user-123', 
                        client = 'c7a8b9d0-1234-5678-9abc-def012345678', 
                        conn_info = { }, 
                        chan_info = { }, ), 
                    offset = 56, 
                    tags = {
                        'key' : ''
                        }, 
                    delta = True, 
                    time = 56, 
                    channel = '', ),
                join = cadenza_client.models.ws_join.wsJoin(
                    info = cadenza_client.models.ws_client_info.wsClientInfo(
                        user = 'user-123', 
                        client = 'c7a8b9d0-1234-5678-9abc-def012345678', 
                        conn_info = { }, 
                        chan_info = { }, ), ),
                leave = cadenza_client.models.ws_leave.wsLeave(
                    info = cadenza_client.models.ws_client_info.wsClientInfo(
                        user = 'user-123', 
                        client = 'c7a8b9d0-1234-5678-9abc-def012345678', 
                        conn_info = { }, 
                        chan_info = { }, ), ),
                unsubscribe = cadenza_client.models.ws_unsubscribe_push.wsUnsubscribePush(
                    code = 56, 
                    reason = '', ),
                message = cadenza_client.models.ws_message.wsMessage(
                    data = { }, ),
                subscribe = cadenza_client.models.ws_subscribe_push.wsSubscribePush(
                    recoverable = True, 
                    epoch = '', 
                    offset = 56, 
                    positioned = True, 
                    data = { }, ),
                connect = cadenza_client.models.ws_connect_push.wsConnectPush(
                    client = '', 
                    version = '', 
                    data = { }, ),
                disconnect = cadenza_client.models.ws_disconnect.wsDisconnect(
                    code = 3000, 
                    reason = 'connection expired', 
                    reconnect = True, ),
                refresh = cadenza_client.models.ws_refresh_push.wsRefreshPush(
                    expires = True, 
                    ttl = 56, )
            )
        else:
            return WsPush(
        )
        """

    def testWsPush(self):
        """Test WsPush"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
