# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.wallet_status import WalletStatus

class TestWalletStatus(unittest.TestCase):
    """WalletStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWalletStatus(self):
        """Test WalletStatus"""
        # inst = WalletStatus()

if __name__ == '__main__':
    unittest.main()
