# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.position_entry import PositionEntry

class TestPositionEntry(unittest.TestCase):
    """PositionEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PositionEntry:
        """Test PositionEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PositionEntry`
        """
        model = PositionEntry()
        if include_optional:
            return PositionEntry(
                position_id = '',
                security_symbol = 'BTC',
                external_position_id = '',
                trading_account_id = '',
                instrument_id = 'BINANCE:BTC/USDT',
                security_type = '',
                status = '',
                quantity = '1234.56789000',
                entry_price = '1234.56789000',
                exit_price = '1234.56789000',
                current_price = '1234.56789000',
                unrealized_pnl = '1234.56789000',
                realized_pnl = '1234.56789000',
                created_at = 1632933600000,
                created_at_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = 1632933600000,
                updated_at_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                closed_at = 1632933600000,
                closed_at_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return PositionEntry(
                position_id = '',
                security_symbol = 'BTC',
                trading_account_id = '',
                security_type = '',
                status = '',
                quantity = '1234.56789000',
                created_at = 1632933600000,
                updated_at = 1632933600000,
        )
        """

    def testPositionEntry(self):
        """Test PositionEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
