# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.operation_status import OperationStatus

class TestOperationStatus(unittest.TestCase):
    """OperationStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOperationStatus(self):
        """Test OperationStatus"""
        # inst = OperationStatus()

if __name__ == '__main__':
    unittest.main()
