# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.balance_entry import BalanceEntry

class TestBalanceEntry(unittest.TestCase):
    """BalanceEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BalanceEntry:
        """Test BalanceEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BalanceEntry`
        """
        model = BalanceEntry()
        if include_optional:
            return BalanceEntry(
                security_symbol = 'USDT',
                security_type = '',
                external_balance_id = '',
                trading_account_id = '',
                status = '',
                position_id = '',
                free = '1234.56789000',
                locked = '1234.56789000',
                borrowed = '1234.56789000',
                total = '1234.56789000',
                net = '1234.56789000',
                updated_at = 1632933600000,
                updated_at_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return BalanceEntry(
                security_symbol = 'USDT',
                security_type = '',
                trading_account_id = '',
                status = '',
                free = '1234.56789000',
                locked = '1234.56789000',
                borrowed = '1234.56789000',
                total = '1234.56789000',
                net = '1234.56789000',
                updated_at = 1632933600000,
        )
        """

    def testBalanceEntry(self):
        """Test BalanceEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
