# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.api.market_api import MarketApi


class TestMarketApi(unittest.TestCase):
    """MarketApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MarketApi()

    def tearDown(self) -> None:
        pass

    def test_delete_market_instrument(self) -> None:
        """Test case for delete_market_instrument

        Delete market instrument
        """
        pass

    def test_delete_market_security(self) -> None:
        """Test case for delete_market_security

        Delete market security
        """
        pass

    def test_disable_market_instrument(self) -> None:
        """Test case for disable_market_instrument

        Disable market instrument
        """
        pass

    def test_enable_market_instrument(self) -> None:
        """Test case for enable_market_instrument

        Enable market instrument
        """
        pass

    def test_get_market_order_book(self) -> None:
        """Test case for get_market_order_book

        Get market order book
        """
        pass

    def test_list_market_instruments(self) -> None:
        """Test case for list_market_instruments

        List market instruments
        """
        pass

    def test_list_market_order_books(self) -> None:
        """Test case for list_market_order_books

        List market order books
        """
        pass

    def test_list_market_securities(self) -> None:
        """Test case for list_market_securities

        List market securities
        """
        pass

    def test_list_market_venues(self) -> None:
        """Test case for list_market_venues

        List market venues
        """
        pass

    def test_sync_market_instruments(self) -> None:
        """Test case for sync_market_instruments

        Sync market instruments
        """
        pass

    def test_sync_market_securities(self) -> None:
        """Test case for sync_market_securities

        Sync market securities
        """
        pass


if __name__ == '__main__':
    unittest.main()
