# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.order_side import OrderSide

class TestOrderSide(unittest.TestCase):
    """OrderSide unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderSide(self):
        """Test OrderSide"""
        # inst = OrderSide()

if __name__ == '__main__':
    unittest.main()
