# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.rpc_list_portfolios_params import RpcListPortfoliosParams

class TestRpcListPortfoliosParams(unittest.TestCase):
    """RpcListPortfoliosParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RpcListPortfoliosParams:
        """Test RpcListPortfoliosParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RpcListPortfoliosParams`
        """
        model = RpcListPortfoliosParams()
        if include_optional:
            return RpcListPortfoliosParams(
                trading_account_id = '',
                venue = '',
                currency = '',
                pagination = cadenza_client.models.rpc_pagination.rpcPagination(
                    offset = 0, 
                    limit = 50, 
                    total = 100, 
                    cursor = '', 
                    has_next = True, )
            )
        else:
            return RpcListPortfoliosParams(
        )
        """

    def testRpcListPortfoliosParams(self):
        """Test RpcListPortfoliosParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
