# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.orderbook import Orderbook

class TestOrderbook(unittest.TestCase):
    """Orderbook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Orderbook:
        """Test Orderbook
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Orderbook`
        """
        model = Orderbook()
        if include_optional:
            return Orderbook(
                instrument_id = 'BINANCE:BTC/USDT',
                venue = '',
                symbol = 'BTC/USDT',
                asks = [
                    [
                        '1234.56789000'
                        ]
                    ],
                bids = [
                    [
                        '1234.56789000'
                        ]
                    ],
                timestamp = 1632933600000
            )
        else:
            return Orderbook(
                venue = '',
                symbol = 'BTC/USDT',
                asks = [
                    [
                        '1234.56789000'
                        ]
                    ],
                bids = [
                    [
                        '1234.56789000'
                        ]
                    ],
                timestamp = 1632933600000,
        )
        """

    def testOrderbook(self):
        """Test Orderbook"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
