# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.rpc_sync_instruments_response import RpcSyncInstrumentsResponse

class TestRpcSyncInstrumentsResponse(unittest.TestCase):
    """RpcSyncInstrumentsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RpcSyncInstrumentsResponse:
        """Test RpcSyncInstrumentsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RpcSyncInstrumentsResponse`
        """
        model = RpcSyncInstrumentsResponse()
        if include_optional:
            return RpcSyncInstrumentsResponse(
                data = cadenza_client.models.rpc_sync_instruments_response_data.rpcSyncInstrumentsResponse_data(
                    total = 56, ),
                error = cadenza_client.models.rpc_error.rpcError(
                    code = -111000, 
                    message = 'Invalid order parameters', 
                    temporary = False, )
            )
        else:
            return RpcSyncInstrumentsResponse(
        )
        """

    def testRpcSyncInstrumentsResponse(self):
        """Test RpcSyncInstrumentsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
