# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.ws_market_order_book_subscribe_params import WsMarketOrderBookSubscribeParams

class TestWsMarketOrderBookSubscribeParams(unittest.TestCase):
    """WsMarketOrderBookSubscribeParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WsMarketOrderBookSubscribeParams:
        """Test WsMarketOrderBookSubscribeParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WsMarketOrderBookSubscribeParams`
        """
        model = WsMarketOrderBookSubscribeParams()
        if include_optional:
            return WsMarketOrderBookSubscribeParams(
                venue = '',
                symbol = 'BTC/USDT',
                depth = 56
            )
        else:
            return WsMarketOrderBookSubscribeParams(
                venue = '',
                symbol = 'BTC/USDT',
        )
        """

    def testWsMarketOrderBookSubscribeParams(self):
        """Test WsMarketOrderBookSubscribeParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
