# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.connect_trading_account200_response import ConnectTradingAccount200Response

class TestConnectTradingAccount200Response(unittest.TestCase):
    """ConnectTradingAccount200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConnectTradingAccount200Response:
        """Test ConnectTradingAccount200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConnectTradingAccount200Response`
        """
        model = ConnectTradingAccount200Response()
        if include_optional:
            return ConnectTradingAccount200Response(
                success = True,
                errno = 0,
                error = '',
                details = cadenza_client.models.base_response_details.baseResponse_details(
                    code = 'INVALID_TOKEN', 
                    resource = '/api/v3/tradingAccount', 
                    action = 'create', 
                    required = ["admin","write"], 
                    provided = ["read"], 
                    tenant_id = 'tenant-123', 
                    request_id = 'req-456-789', 
                    metadata = { }, ),
                data = cadenza_client.models.trading_account.tradingAccount(
                    trading_account_id = '', 
                    external_trading_account_id = '', 
                    venue = '', 
                    nickname = '', 
                    account_type = 'SPOT', 
                    credentials = [
                        cadenza_client.models.trading_account_credential.tradingAccountCredential(
                            credential_id = '', 
                            venue = '', 
                            credential_type = '', 
                            nickname = 'api_key_for_binance', 
                            status = 'CREATED', 
                            created_at = 1632933600000, 
                            created_at_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = 1632933600000, 
                            updated_at_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            revoked_at = 1632933600000, 
                            revoked_at_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    status = 'ACTIVE', 
                    created_at = 1632933600000, 
                    created_at_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = 1632933600000, 
                    updated_at_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return ConnectTradingAccount200Response(
                success = True,
                errno = 0,
                error = '',
        )
        """

    def testConnectTradingAccount200Response(self):
        """Test ConnectTradingAccount200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
