# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.api.market_subscription_api import MarketSubscriptionApi


class TestMarketSubscriptionApi(unittest.TestCase):
    """MarketSubscriptionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MarketSubscriptionApi()

    def tearDown(self) -> None:
        pass

    def test_list_market_order_book_subscriptions(self) -> None:
        """Test case for list_market_order_book_subscriptions

        List order book subscriptions
        """
        pass

    def test_subscribe_market_order_book(self) -> None:
        """Test case for subscribe_market_order_book

        Subscribe to order book updates
        """
        pass

    def test_unsubscribe_market_order_book(self) -> None:
        """Test case for unsubscribe_market_order_book

        Unsubscribe from order book updates
        """
        pass


if __name__ == '__main__':
    unittest.main()
