# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.root200_response_all_of_data import Root200ResponseAllOfData

class TestRoot200ResponseAllOfData(unittest.TestCase):
    """Root200ResponseAllOfData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Root200ResponseAllOfData:
        """Test Root200ResponseAllOfData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Root200ResponseAllOfData`
        """
        model = Root200ResponseAllOfData()
        if include_optional:
            return Root200ResponseAllOfData(
                name = 'Algo724 Cadenza Fermata API',
                version = '3.0.1',
                description = 'Unified trading platform for connecting to multiple venues, executing orders, and accessing real-time market data',
                documentation = 'https://docs.algo724.com/api/v3'
            )
        else:
            return Root200ResponseAllOfData(
        )
        """

    def testRoot200ResponseAllOfData(self):
        """Test Root200ResponseAllOfData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
