# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.rpc_method import RpcMethod

class TestRpcMethod(unittest.TestCase):
    """RpcMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRpcMethod(self):
        """Test RpcMethod"""
        # inst = RpcMethod()

if __name__ == '__main__':
    unittest.main()
