# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.rpc_order_book_updated_event import RpcOrderBookUpdatedEvent

class TestRpcOrderBookUpdatedEvent(unittest.TestCase):
    """RpcOrderBookUpdatedEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RpcOrderBookUpdatedEvent:
        """Test RpcOrderBookUpdatedEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RpcOrderBookUpdatedEvent`
        """
        model = RpcOrderBookUpdatedEvent()
        if include_optional:
            return RpcOrderBookUpdatedEvent(
                data = cadenza_client.models.rpc_order_book.rpcOrderBook(
                    instrument_id = 'BINANCE:BTC/USDT', 
                    venue = '', 
                    symbol = '', 
                    bids = [
                        cadenza_client.models.rpc_order_book_level.rpcOrderBookLevel(
                            price = '50000.00', 
                            quantity = '1.5', )
                        ], 
                    asks = [
                        cadenza_client.models.rpc_order_book_level.rpcOrderBookLevel(
                            price = '50000.00', 
                            quantity = '1.5', )
                        ], 
                    timestamp = 56, 
                    sequence_number = 56, )
            )
        else:
            return RpcOrderBookUpdatedEvent(
        )
        """

    def testRpcOrderBookUpdatedEvent(self):
        """Test RpcOrderBookUpdatedEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
