# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.rpc_list_trading_account_operations_response import RpcListTradingAccountOperationsResponse

class TestRpcListTradingAccountOperationsResponse(unittest.TestCase):
    """RpcListTradingAccountOperationsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RpcListTradingAccountOperationsResponse:
        """Test RpcListTradingAccountOperationsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RpcListTradingAccountOperationsResponse`
        """
        model = RpcListTradingAccountOperationsResponse()
        if include_optional:
            return RpcListTradingAccountOperationsResponse(
                data = [
                    cadenza_client.models.rpc_trading_account_operation_history.rpcTradingAccountOperationHistory(
                        trading_account_history_id = '', 
                        trading_account_id = '', 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        operation_type = 'CONNECTED', 
                        operate_by = '', 
                        tags = [
                            ''
                            ], 
                        previous_values = cadenza_client.models.previous_values.previousValues(), 
                        new_values = cadenza_client.models.new_values.newValues(), )
                    ],
                error = cadenza_client.models.rpc_error.rpcError(
                    code = -111000, 
                    message = 'Invalid order parameters', 
                    temporary = False, )
            )
        else:
            return RpcListTradingAccountOperationsResponse(
        )
        """

    def testRpcListTradingAccountOperationsResponse(self):
        """Test RpcListTradingAccountOperationsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
