# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.ws_rpc_request_data import WsRPCRequestData

class TestWsRPCRequestData(unittest.TestCase):
    """WsRPCRequestData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WsRPCRequestData:
        """Test WsRPCRequestData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WsRPCRequestData`
        """
        model = WsRPCRequestData()
        if include_optional:
            return WsRPCRequestData(
                trade_order = cadenza_client.models.rpc_trade_order.rpcTradeOrder(
                    trade_order_id = '', 
                    client_order_id = '', 
                    original_client_order_id = '', 
                    external_order_id = '', 
                    idempotency_key = '', 
                    venue = 'BINANCE', 
                    trading_account_id = '', 
                    external_trading_account_id = '', 
                    instrument_id = 'BINANCE:BTC/USDT', 
                    external_symbol = 'BTCUSDT', 
                    base_asset = 'BTC', 
                    quote_asset = 'USDT', 
                    order_type = 'LIMIT', 
                    order_side = 'BUY', 
                    quantity_type = 'BASE', 
                    quantity = '1.5', 
                    quote_currency_quantity = '', 
                    position_percentage = '', 
                    quantity_rounding = '', 
                    limit_price = '50000.00', 
                    stop_price = '', 
                    time_in_force = 'GTC', 
                    status = 'FILLED', 
                    executed_price = '', 
                    executed_percentage = '', 
                    executed_quantity = '', 
                    executed_cost = '', 
                    fees = [
                        cadenza_client.models.rpc_security_quantity.rpcSecurityQuantity(
                            asset = 'BTC', 
                            quantity = '0.001', )
                        ], 
                    cancel_reason = '', 
                    reject_reason = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    expire_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_execution_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    canceled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                trading_account_id = '',
                idempotency_key = '',
                await_closed = True,
                trade_order_id = '',
                client_order_id = '',
                external_order_id = '',
                instrument_id = [
                    ''
                    ],
                side = 'BUY',
                order_type = 'LIMIT',
                status = 'VALIDATED',
                start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                pagination = cadenza_client.models.rpc_pagination.rpcPagination(
                    offset = 0, 
                    limit = 50, 
                    total = 100, 
                    cursor = '', 
                    has_next = True, ),
                trading_account = cadenza_client.models.rpc_trading_account.rpcTradingAccount(
                    trading_account_id = '', 
                    client_id = '', 
                    nickname = 'My Binance Account', 
                    external_account_id = '', 
                    venue = 'BINANCE', 
                    status = 'ACTIVE', 
                    account_type = 'SPOT', 
                    credentials = [
                        cadenza_client.models.rpc_trading_account_credential.rpcTradingAccountCredential(
                            credential_id = '', 
                            nickname = '', 
                            credential_type = 'API_KEY', 
                            api_key = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            revoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            with_info = True, 
                            with_secret = True, )
                        ], 
                    config = cadenza_client.models.rpc_trading_account_config.rpcTradingAccountConfig(
                        leverage = 56, ), 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                trading_accounts = [
                    cadenza_client.models.rpc_trading_account.rpcTradingAccount(
                        trading_account_id = '', 
                        client_id = '', 
                        nickname = 'My Binance Account', 
                        external_account_id = '', 
                        venue = 'BINANCE', 
                        status = 'ACTIVE', 
                        account_type = 'SPOT', 
                        credentials = [
                            cadenza_client.models.rpc_trading_account_credential.rpcTradingAccountCredential(
                                credential_id = '', 
                                nickname = '', 
                                credential_type = 'API_KEY', 
                                api_key = '', 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                revoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                with_info = True, 
                                with_secret = True, )
                            ], 
                        config = cadenza_client.models.rpc_trading_account_config.rpcTradingAccountConfig(
                            leverage = 56, ), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                venue = 'BINANCE',
                subscription_type = 'MARKET.SUBSCRIPTION.ORDERBOOK',
                subscription_id = '',
                credential_type = 'API_KEY',
                api_key = '',
                secret_key = '',
                secret_passphrase = '',
                nickname = '',
                credential = cadenza_client.models.rpc_trading_account_credential.rpcTradingAccountCredential(
                    credential_id = '', 
                    nickname = '', 
                    credential_type = 'API_KEY', 
                    status = 'VALIDATED', 
                    venue = 'BINANCE', 
                    api_key = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    revoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    with_info = True, 
                    with_secret = True, ),
                credential_ids = [
                    ''
                    ],
                credentials = [
                    cadenza_client.models.rpc_trading_account_credential.rpcTradingAccountCredential(
                        credential_id = '', 
                        nickname = '', 
                        credential_type = 'API_KEY', 
                        status = 'VALIDATED', 
                        venue = 'BINANCE', 
                        api_key = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        revoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        with_info = True, 
                        with_secret = True, )
                    ],
                credential_id = '',
                currency = '',
                portfolio = cadenza_client.models.rpc_portfolio.rpcPortfolio(
                    trading_account_id = '', 
                    account_info = cadenza_client.models.rpc_trading_account.rpcTradingAccount(
                        trading_account_id = '', 
                        client_id = '', 
                        nickname = 'My Binance Account', 
                        external_account_id = '', 
                        venue = 'BINANCE', 
                        status = 'ACTIVE', 
                        account_type = 'SPOT', 
                        credentials = [
                            cadenza_client.models.rpc_trading_account_credential.rpcTradingAccountCredential(
                                credential_id = '', 
                                nickname = '', 
                                credential_type = 'API_KEY', 
                                api_key = '', 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                revoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                with_info = True, 
                                with_secret = True, )
                            ], 
                        config = cadenza_client.models.rpc_trading_account_config.rpcTradingAccountConfig(
                            leverage = 56, ), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    balances = [
                        cadenza_client.models.rpc_balance_entry.rpcBalanceEntry(
                            balance_id = '', 
                            external_balance_id = '', 
                            trading_account_id = '', 
                            security_symbol = 'BTC', 
                            security_type = 'CRYPTO', 
                            free = '', 
                            locked = '', 
                            frozen = '', 
                            borrowed = '', 
                            interest_owed = '', 
                            total = '', 
                            net = '', 
                            collateral_weight = '', 
                            collateral_value = '', 
                            collateral_enabled = True, 
                            cross_margin = '', 
                            isolated_margin = '', 
                            margin_ratio = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    positions = [
                        cadenza_client.models.rpc_position_entry.rpcPositionEntry(
                            position_id = '', 
                            external_position_id = '', 
                            trading_account_id = '', 
                            security_symbol = '', 
                            instrument_id = '', 
                            quantity = '', 
                            entry_price = '', 
                            exit_price = '', 
                            current_price = '', 
                            unrealized_pnl = '', 
                            realized_pnl = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    summary = cadenza_client.models.rpc_portfolio_summary.rpcPortfolioSummary(
                        portfolio_summary_id = '', 
                        trading_account_id = '', 
                        currency = 'USDT', 
                        leverage = 56, 
                        equity = '', 
                        margin = '', 
                        margin_loan = '', 
                        margin_usage = '', 
                        margin_requirement = '', 
                        margin_level = '', 
                        credit = '', 
                        risk_exposure = '', 
                        max_risk_exposure = '', 
                        risk_exposure_rate = '', ), 
                    update_mode = 'SNAPSHOT', 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                symbols = [
                    ''
                    ],
                instruments = [
                    ''
                    ],
                security_type = '',
                instrument_status = '',
                limit = 56,
                offset = 56,
                securities = [
                    ''
                    ],
                security_ids = [
                    ''
                    ],
                external_symbols = [
                    ''
                    ],
                symbol = '',
                depth = 56,
                instrument_ids = [
                    ''
                    ],
                order_books = [
                    cadenza_client.models.rpc_order_book.rpcOrderBook(
                        instrument_id = 'BINANCE:BTC/USDT', 
                        venue = '', 
                        symbol = '', 
                        bids = [
                            cadenza_client.models.rpc_order_book_level.rpcOrderBookLevel(
                                price = '50000.00', 
                                quantity = '1.5', )
                            ], 
                        asks = [
                            cadenza_client.models.rpc_order_book_level.rpcOrderBookLevel(
                                price = '50000.00', 
                                quantity = '1.5', )
                            ], 
                        timestamp = 56, 
                        sequence_number = 56, )
                    ],
                klines = [
                    cadenza_client.models.rpc_kline.rpcKline(
                        instrument_id = 'BINANCE:BTC/USDT', 
                        symbol = '', 
                        interval = '1h', 
                        candles = [
                            cadenza_client.models.rpc_ohlcv.rpcOhlcv(
                                t = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                interval = '', 
                                o = '', 
                                h = '', 
                                l = '', 
                                c = '', 
                                v = '', )
                            ], )
                    ],
                interval = '1h',
                tickers = [
                    cadenza_client.models.rpc_ticker.rpcTicker(
                        instrument_id = 'BINANCE:BTC/USDT', 
                        symbol = '', 
                        exchange = '', 
                        exchange_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        ask = '', 
                        ask_quantity = '', 
                        bid = '', 
                        bid_quantity = '', 
                        last = '', 
                        last_quantity = '', )
                    ]
            )
        else:
            return WsRPCRequestData(
                trade_order = cadenza_client.models.rpc_trade_order.rpcTradeOrder(
                    trade_order_id = '', 
                    client_order_id = '', 
                    original_client_order_id = '', 
                    external_order_id = '', 
                    idempotency_key = '', 
                    venue = 'BINANCE', 
                    trading_account_id = '', 
                    external_trading_account_id = '', 
                    instrument_id = 'BINANCE:BTC/USDT', 
                    external_symbol = 'BTCUSDT', 
                    base_asset = 'BTC', 
                    quote_asset = 'USDT', 
                    order_type = 'LIMIT', 
                    order_side = 'BUY', 
                    quantity_type = 'BASE', 
                    quantity = '1.5', 
                    quote_currency_quantity = '', 
                    position_percentage = '', 
                    quantity_rounding = '', 
                    limit_price = '50000.00', 
                    stop_price = '', 
                    time_in_force = 'GTC', 
                    status = 'FILLED', 
                    executed_price = '', 
                    executed_percentage = '', 
                    executed_quantity = '', 
                    executed_cost = '', 
                    fees = [
                        cadenza_client.models.rpc_security_quantity.rpcSecurityQuantity(
                            asset = 'BTC', 
                            quantity = '0.001', )
                        ], 
                    cancel_reason = '', 
                    reject_reason = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    expire_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_execution_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    canceled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                trading_account_id = '',
                trade_order_id = '',
                instrument_id = [
                    ''
                    ],
                trading_account = cadenza_client.models.rpc_trading_account.rpcTradingAccount(
                    trading_account_id = '', 
                    client_id = '', 
                    nickname = 'My Binance Account', 
                    external_account_id = '', 
                    venue = 'BINANCE', 
                    status = 'ACTIVE', 
                    account_type = 'SPOT', 
                    credentials = [
                        cadenza_client.models.rpc_trading_account_credential.rpcTradingAccountCredential(
                            credential_id = '', 
                            nickname = '', 
                            credential_type = 'API_KEY', 
                            api_key = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            revoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            with_info = True, 
                            with_secret = True, )
                        ], 
                    config = cadenza_client.models.rpc_trading_account_config.rpcTradingAccountConfig(
                        leverage = 56, ), 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                trading_accounts = [
                    cadenza_client.models.rpc_trading_account.rpcTradingAccount(
                        trading_account_id = '', 
                        client_id = '', 
                        nickname = 'My Binance Account', 
                        external_account_id = '', 
                        venue = 'BINANCE', 
                        status = 'ACTIVE', 
                        account_type = 'SPOT', 
                        credentials = [
                            cadenza_client.models.rpc_trading_account_credential.rpcTradingAccountCredential(
                                credential_id = '', 
                                nickname = '', 
                                credential_type = 'API_KEY', 
                                api_key = '', 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                revoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                with_info = True, 
                                with_secret = True, )
                            ], 
                        config = cadenza_client.models.rpc_trading_account_config.rpcTradingAccountConfig(
                            leverage = 56, ), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                venue = 'BINANCE',
                subscription_type = 'MARKET.SUBSCRIPTION.ORDERBOOK',
                credential_type = 'API_KEY',
                credential = cadenza_client.models.rpc_trading_account_credential.rpcTradingAccountCredential(
                    credential_id = '', 
                    nickname = '', 
                    credential_type = 'API_KEY', 
                    status = 'VALIDATED', 
                    venue = 'BINANCE', 
                    api_key = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    revoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    with_info = True, 
                    with_secret = True, ),
                credential_id = '',
                portfolio = cadenza_client.models.rpc_portfolio.rpcPortfolio(
                    trading_account_id = '', 
                    account_info = cadenza_client.models.rpc_trading_account.rpcTradingAccount(
                        trading_account_id = '', 
                        client_id = '', 
                        nickname = 'My Binance Account', 
                        external_account_id = '', 
                        venue = 'BINANCE', 
                        status = 'ACTIVE', 
                        account_type = 'SPOT', 
                        credentials = [
                            cadenza_client.models.rpc_trading_account_credential.rpcTradingAccountCredential(
                                credential_id = '', 
                                nickname = '', 
                                credential_type = 'API_KEY', 
                                api_key = '', 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                revoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                with_info = True, 
                                with_secret = True, )
                            ], 
                        config = cadenza_client.models.rpc_trading_account_config.rpcTradingAccountConfig(
                            leverage = 56, ), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    balances = [
                        cadenza_client.models.rpc_balance_entry.rpcBalanceEntry(
                            balance_id = '', 
                            external_balance_id = '', 
                            trading_account_id = '', 
                            security_symbol = 'BTC', 
                            security_type = 'CRYPTO', 
                            free = '', 
                            locked = '', 
                            frozen = '', 
                            borrowed = '', 
                            interest_owed = '', 
                            total = '', 
                            net = '', 
                            collateral_weight = '', 
                            collateral_value = '', 
                            collateral_enabled = True, 
                            cross_margin = '', 
                            isolated_margin = '', 
                            margin_ratio = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    positions = [
                        cadenza_client.models.rpc_position_entry.rpcPositionEntry(
                            position_id = '', 
                            external_position_id = '', 
                            trading_account_id = '', 
                            security_symbol = '', 
                            instrument_id = '', 
                            quantity = '', 
                            entry_price = '', 
                            exit_price = '', 
                            current_price = '', 
                            unrealized_pnl = '', 
                            realized_pnl = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    summary = cadenza_client.models.rpc_portfolio_summary.rpcPortfolioSummary(
                        portfolio_summary_id = '', 
                        trading_account_id = '', 
                        currency = 'USDT', 
                        leverage = 56, 
                        equity = '', 
                        margin = '', 
                        margin_loan = '', 
                        margin_usage = '', 
                        margin_requirement = '', 
                        margin_level = '', 
                        credit = '', 
                        risk_exposure = '', 
                        max_risk_exposure = '', 
                        risk_exposure_rate = '', ), 
                    update_mode = 'SNAPSHOT', 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                instruments = [
                    ''
                    ],
                securities = [
                    ''
                    ],
                security_ids = [
                    ''
                    ],
                order_books = [
                    cadenza_client.models.rpc_order_book.rpcOrderBook(
                        instrument_id = 'BINANCE:BTC/USDT', 
                        venue = '', 
                        symbol = '', 
                        bids = [
                            cadenza_client.models.rpc_order_book_level.rpcOrderBookLevel(
                                price = '50000.00', 
                                quantity = '1.5', )
                            ], 
                        asks = [
                            cadenza_client.models.rpc_order_book_level.rpcOrderBookLevel(
                                price = '50000.00', 
                                quantity = '1.5', )
                            ], 
                        timestamp = 56, 
                        sequence_number = 56, )
                    ],
                klines = [
                    cadenza_client.models.rpc_kline.rpcKline(
                        instrument_id = 'BINANCE:BTC/USDT', 
                        symbol = '', 
                        interval = '1h', 
                        candles = [
                            cadenza_client.models.rpc_ohlcv.rpcOhlcv(
                                t = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                interval = '', 
                                o = '', 
                                h = '', 
                                l = '', 
                                c = '', 
                                v = '', )
                            ], )
                    ],
                tickers = [
                    cadenza_client.models.rpc_ticker.rpcTicker(
                        instrument_id = 'BINANCE:BTC/USDT', 
                        symbol = '', 
                        exchange = '', 
                        exchange_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        ask = '', 
                        ask_quantity = '', 
                        bid = '', 
                        bid_quantity = '', 
                        last = '', 
                        last_quantity = '', )
                    ],
        )
        """

    def testWsRPCRequestData(self):
        """Test WsRPCRequestData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
