# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.rpc_subscription_updated_event import RpcSubscriptionUpdatedEvent

class TestRpcSubscriptionUpdatedEvent(unittest.TestCase):
    """RpcSubscriptionUpdatedEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RpcSubscriptionUpdatedEvent:
        """Test RpcSubscriptionUpdatedEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RpcSubscriptionUpdatedEvent`
        """
        model = RpcSubscriptionUpdatedEvent()
        if include_optional:
            return RpcSubscriptionUpdatedEvent(
                data = [
                    cadenza_client.models.rpc_subscription.rpcSubscription(
                        subscription_id = '', 
                        instrument_id = '', 
                        venue = 'BINANCE', 
                        subscription_type = 'MARKET.SUBSCRIPTION.ORDERBOOK', 
                        status = 'ACTIVE', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return RpcSubscriptionUpdatedEvent(
        )
        """

    def testRpcSubscriptionUpdatedEvent(self):
        """Test RpcSubscriptionUpdatedEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
