# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.api.authentication_api import AuthenticationApi


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthenticationApi()

    def tearDown(self) -> None:
        pass

    def test_auth_get_user(self) -> None:
        """Test case for auth_get_user

        Get current user
        """
        pass

    def test_auth_login(self) -> None:
        """Test case for auth_login

        Login with email and password
        """
        pass

    def test_auth_logout(self) -> None:
        """Test case for auth_logout

        Logout user
        """
        pass

    def test_auth_recover(self) -> None:
        """Test case for auth_recover

        Request password recovery
        """
        pass

    def test_auth_refresh_token(self) -> None:
        """Test case for auth_refresh_token

        Refresh access token
        """
        pass

    def test_auth_signup(self) -> None:
        """Test case for auth_signup

        Sign up new user
        """
        pass

    def test_auth_update_user(self) -> None:
        """Test case for auth_update_user

        Update current user
        """
        pass


if __name__ == '__main__':
    unittest.main()
