# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.base_event import BaseEvent

class TestBaseEvent(unittest.TestCase):
    """BaseEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BaseEvent:
        """Test BaseEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BaseEvent`
        """
        model = BaseEvent()
        if include_optional:
            return BaseEvent(
                metadata = cadenza_client.models.event_metadata.eventMetadata(
                    trace_id = 'trace-123-456-789', 
                    event_id = '', 
                    event_type = 'command.tradeOrder.submit', 
                    timestamp = 1632933600000, 
                    sender = 'TRADE_ORDER_SERVICE', 
                    receiver = 'TRADE_ORDER_SERVICE', ),
                data = None
            )
        else:
            return BaseEvent(
                metadata = cadenza_client.models.event_metadata.eventMetadata(
                    trace_id = 'trace-123-456-789', 
                    event_id = '', 
                    event_type = 'command.tradeOrder.submit', 
                    timestamp = 1632933600000, 
                    sender = 'TRADE_ORDER_SERVICE', 
                    receiver = 'TRADE_ORDER_SERVICE', ),
                data = None,
        )
        """

    def testBaseEvent(self):
        """Test BaseEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
