# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.list_market_order_books200_response import ListMarketOrderBooks200Response

class TestListMarketOrderBooks200Response(unittest.TestCase):
    """ListMarketOrderBooks200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListMarketOrderBooks200Response:
        """Test ListMarketOrderBooks200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListMarketOrderBooks200Response`
        """
        model = ListMarketOrderBooks200Response()
        if include_optional:
            return ListMarketOrderBooks200Response(
                success = True,
                errno = 0,
                error = '',
                details = cadenza_client.models.base_response_details.baseResponse_details(
                    code = 'INVALID_TOKEN', 
                    resource = '/api/v3/tradingAccount', 
                    action = 'create', 
                    required = ["admin","write"], 
                    provided = ["read"], 
                    tenant_id = 'tenant-123', 
                    request_id = 'req-456-789', 
                    metadata = { }, ),
                data = [
                    cadenza_client.models.orderbook.orderbook(
                        instrument_id = 'BINANCE:BTC/USDT', 
                        venue = '', 
                        symbol = 'BTC/USDT', 
                        asks = [
                            [
                                '1234.56789000'
                                ]
                            ], 
                        bids = [
                            [
                                '1234.56789000'
                                ]
                            ], 
                        timestamp = 1632933600000, )
                    ]
            )
        else:
            return ListMarketOrderBooks200Response(
                success = True,
                errno = 0,
                error = '',
        )
        """

    def testListMarketOrderBooks200Response(self):
        """Test ListMarketOrderBooks200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
