# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.auth_signup429_response import AuthSignup429Response

class TestAuthSignup429Response(unittest.TestCase):
    """AuthSignup429Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthSignup429Response:
        """Test AuthSignup429Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthSignup429Response`
        """
        model = AuthSignup429Response()
        if include_optional:
            return AuthSignup429Response(
                success = True,
                errno = 0,
                error = '',
                details = cadenza_client.models.base_response_details.baseResponse_details(
                    code = 'INVALID_TOKEN', 
                    resource = '/api/v3/tradingAccount', 
                    action = 'create', 
                    required = ["admin","write"], 
                    provided = ["read"], 
                    tenant_id = 'tenant-123', 
                    request_id = 'req-456-789', 
                    metadata = { }, ),
                data = 'Too many requests'
            )
        else:
            return AuthSignup429Response(
                success = True,
                errno = 0,
                error = '',
        )
        """

    def testAuthSignup429Response(self):
        """Test AuthSignup429Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
