# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.get_trade_order_query import GetTradeOrderQuery

class TestGetTradeOrderQuery(unittest.TestCase):
    """GetTradeOrderQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTradeOrderQuery:
        """Test GetTradeOrderQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTradeOrderQuery`
        """
        model = GetTradeOrderQuery()
        if include_optional:
            return GetTradeOrderQuery(
                metadata = cadenza_client.models.query_metadata.queryMetadata(
                    trace_id = '', 
                    event_id = '', 
                    event_type = 'command.tradeOrder.submit', 
                    timestamp = 1632933600000, 
                    sender = 'TRADE_ORDER_SERVICE', 
                    receiver = 'TRADE_ORDER_SERVICE', ),
                data = cadenza_client.models.get_trade_order_query_data.getTradeOrderQuery_data(
                    order_id = '', )
            )
        else:
            return GetTradeOrderQuery(
                metadata = cadenza_client.models.query_metadata.queryMetadata(
                    trace_id = '', 
                    event_id = '', 
                    event_type = 'command.tradeOrder.submit', 
                    timestamp = 1632933600000, 
                    sender = 'TRADE_ORDER_SERVICE', 
                    receiver = 'TRADE_ORDER_SERVICE', ),
                data = cadenza_client.models.get_trade_order_query_data.getTradeOrderQuery_data(
                    order_id = '', ),
        )
        """

    def testGetTradeOrderQuery(self):
        """Test GetTradeOrderQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
