# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.ws_client_info import WsClientInfo

class TestWsClientInfo(unittest.TestCase):
    """WsClientInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WsClientInfo:
        """Test WsClientInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WsClientInfo`
        """
        model = WsClientInfo()
        if include_optional:
            return WsClientInfo(
                user = 'user-123',
                client = 'c7a8b9d0-1234-5678-9abc-def012345678',
                conn_info = { },
                chan_info = { }
            )
        else:
            return WsClientInfo(
        )
        """

    def testWsClientInfo(self):
        """Test WsClientInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
