# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.health200_response import Health200Response

class TestHealth200Response(unittest.TestCase):
    """Health200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Health200Response:
        """Test Health200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Health200Response`
        """
        model = Health200Response()
        if include_optional:
            return Health200Response(
                status = 'healthy',
                timestamp = 1632933600000,
                timestamp_iso = '2023-09-29T12:00Z',
                version = '3.0.1',
                checks = cadenza_client.models.health_200_response_checks.health_200_response_checks(
                    database = cadenza_client.models.health_check_component.healthCheckComponent(
                        status = 'healthy', ), 
                    temporal = cadenza_client.models.health_check_component.healthCheckComponent(
                        status = 'healthy', ), 
                    redis = , )
            )
        else:
            return Health200Response(
                status = 'healthy',
                timestamp = 1632933600000,
                timestamp_iso = '2023-09-29T12:00Z',
                version = '3.0.1',
        )
        """

    def testHealth200Response(self):
        """Test Health200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
