# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.rpc_list_trade_orders_request import RpcListTradeOrdersRequest

class TestRpcListTradeOrdersRequest(unittest.TestCase):
    """RpcListTradeOrdersRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RpcListTradeOrdersRequest:
        """Test RpcListTradeOrdersRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RpcListTradeOrdersRequest`
        """
        model = RpcListTradeOrdersRequest()
        if include_optional:
            return RpcListTradeOrdersRequest(
                trade_order_id = '',
                trading_account_id = '',
                instrument_id = '',
                side = 'BUY',
                order_type = 'LIMIT',
                status = 'FILLED',
                start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                pagination = cadenza_client.models.rpc_pagination.rpcPagination(
                    offset = 0, 
                    limit = 50, 
                    total = 100, 
                    cursor = '', 
                    has_next = True, )
            )
        else:
            return RpcListTradeOrdersRequest(
        )
        """

    def testRpcListTradeOrdersRequest(self):
        """Test RpcListTradeOrdersRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
