# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cadenza_client.models.sync_market_instruments_request import SyncMarketInstrumentsRequest

class TestSyncMarketInstrumentsRequest(unittest.TestCase):
    """SyncMarketInstrumentsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncMarketInstrumentsRequest:
        """Test SyncMarketInstrumentsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncMarketInstrumentsRequest`
        """
        model = SyncMarketInstrumentsRequest()
        if include_optional:
            return SyncMarketInstrumentsRequest(
                venue = '',
                symbols = [
                    ''
                    ]
            )
        else:
            return SyncMarketInstrumentsRequest(
                venue = '',
                symbols = [
                    ''
                    ],
        )
        """

    def testSyncMarketInstrumentsRequest(self):
        """Test SyncMarketInstrumentsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
