# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class BaseResponseDetails(BaseModel):
    """
    Additional error details (optional, only present in error responses)
    """ # noqa: E501
    code: Optional[StrictStr] = Field(default=None, description="Error code identifier (e.g., INVALID_TOKEN, ACCESS_DENIED)")
    resource: Optional[StrictStr] = Field(default=None, description="Resource that was being accessed")
    action: Optional[StrictStr] = Field(default=None, description="Action that was being attempted")
    required: Optional[List[StrictStr]] = Field(default=None, description="Required permissions or roles")
    provided: Optional[List[StrictStr]] = Field(default=None, description="Provided permissions or roles")
    tenant_id: Optional[StrictStr] = Field(default=None, description="Tenant ID if relevant to the error")
    request_id: Optional[StrictStr] = Field(default=None, description="Request ID for tracking and debugging")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Additional metadata as key-value pairs")
    __properties: ClassVar[List[str]] = ["code", "resource", "action", "required", "provided", "tenant_id", "request_id", "metadata"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BaseResponseDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BaseResponseDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "code": obj.get("code"),
            "resource": obj.get("resource"),
            "action": obj.get("action"),
            "required": obj.get("required"),
            "provided": obj.get("provided"),
            "tenant_id": obj.get("tenant_id"),
            "request_id": obj.get("request_id"),
            "metadata": obj.get("metadata")
        })
        return _obj


