# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cadenza_client.models.instrument_status import InstrumentStatus
from cadenza_client.models.instrument_type import InstrumentType
from cadenza_client.models.order_type import OrderType
from cadenza_client.models.security_type import SecurityType
from cadenza_client.models.time_in_force import TimeInForce
from cadenza_client.models.venue import Venue
from typing import Optional, Set
from typing_extensions import Self

class Instrument(BaseModel):
    """
    Instrument
    """ # noqa: E501
    instrument_id: StrictStr = Field(description="Instrument ID in format {VENUE}:{BASE}/{QUOTE}", alias="instrumentId")
    venue: Venue
    symbol: StrictStr = Field(description="Human-readable symbol format")
    external_symbol: StrictStr = Field(description="Symbol format used by the exchange", alias="externalSymbol")
    description: Optional[StrictStr] = Field(default=None, description="Symbol description, human readable description of the instrument")
    instrument_type: InstrumentType = Field(alias="instrumentType")
    status: InstrumentStatus
    base_asset: StrictStr = Field(alias="baseAsset")
    quote_asset: StrictStr = Field(alias="quoteAsset")
    base_security_type: SecurityType = Field(alias="baseSecurityType")
    quote_security_type: SecurityType = Field(alias="quoteSecurityType")
    base_precision: StrictInt = Field(description="Base asset precision", alias="basePrecision")
    quote_precision: StrictInt = Field(description="Quote asset precision", alias="quotePrecision")
    base_max_significant: Optional[StrictInt] = Field(description="Maximum significant digits for base asset", alias="baseMaxSignificant")
    quote_max_significant: Optional[StrictInt] = Field(description="Maximum significant digits for quote asset", alias="quoteMaxSignificant")
    lot_size: Annotated[str, Field(strict=True)] = Field(description="Decimal value as string to preserve precision", alias="lotSize")
    pip_size: Annotated[str, Field(strict=True)] = Field(description="Decimal value as string to preserve precision", alias="pipSize")
    base_scale: Optional[StrictInt] = Field(description="Base asset scale factor", alias="baseScale")
    quote_scale: Optional[StrictInt] = Field(description="Quote asset scale factor", alias="quoteScale")
    min_quantity: Annotated[str, Field(strict=True)] = Field(description="Decimal value as string to preserve precision", alias="minQuantity")
    max_quantity: Annotated[str, Field(strict=True)] = Field(description="Decimal value as string to preserve precision", alias="maxQuantity")
    min_notional: Annotated[str, Field(strict=True)] = Field(description="Decimal value as string to preserve precision", alias="minNotional")
    max_notional: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Decimal value as string to preserve precision", alias="maxNotional")
    order_filters: Optional[Dict[str, Any]] = Field(default=None, description="Exchange-specific order filters", alias="orderFilters")
    order_types: List[OrderType] = Field(alias="orderTypes")
    time_in_force_options: List[TimeInForce] = Field(alias="timeInForceOptions")
    trading_hours: Optional[Dict[str, Any]] = Field(default=None, description="Trading hours and schedule information", alias="tradingHours")
    is_iceberg_allowed: Optional[StrictBool] = Field(default=None, description="Whether iceberg orders are allowed", alias="isIcebergAllowed")
    iceberg_min_quantity: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Decimal value as string to preserve precision", alias="icebergMinQuantity")
    delivery_date: Optional[StrictInt] = Field(default=None, description="Unix timestamp in milliseconds", alias="deliveryDate")
    delivery_date_time: Optional[datetime] = Field(default=None, description="Delivery date in ISO 8601 format for derivatives", alias="deliveryDateTime")
    exercise_style: Optional[StrictStr] = Field(default=None, description="Exercise style for options", alias="exerciseStyle")
    strike_price: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Decimal value as string to preserve precision", alias="strikePrice")
    __properties: ClassVar[List[str]] = ["instrumentId", "venue", "symbol", "externalSymbol", "description", "instrumentType", "status", "baseAsset", "quoteAsset", "baseSecurityType", "quoteSecurityType", "basePrecision", "quotePrecision", "baseMaxSignificant", "quoteMaxSignificant", "lotSize", "pipSize", "baseScale", "quoteScale", "minQuantity", "maxQuantity", "minNotional", "maxNotional", "orderFilters", "orderTypes", "timeInForceOptions", "tradingHours", "isIcebergAllowed", "icebergMinQuantity", "deliveryDate", "deliveryDateTime", "exerciseStyle", "strikePrice"]

    @field_validator('lot_size')
    def lot_size_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('pip_size')
    def pip_size_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('min_quantity')
    def min_quantity_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('max_quantity')
    def max_quantity_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('min_notional')
    def min_notional_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('max_notional')
    def max_notional_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('iceberg_min_quantity')
    def iceberg_min_quantity_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('exercise_style')
    def exercise_style_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['EUROPEAN', 'AMERICAN']):
            raise ValueError("must be one of enum values ('EUROPEAN', 'AMERICAN')")
        return value

    @field_validator('strike_price')
    def strike_price_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Instrument from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if base_max_significant (nullable) is None
        # and model_fields_set contains the field
        if self.base_max_significant is None and "base_max_significant" in self.model_fields_set:
            _dict['baseMaxSignificant'] = None

        # set to None if quote_max_significant (nullable) is None
        # and model_fields_set contains the field
        if self.quote_max_significant is None and "quote_max_significant" in self.model_fields_set:
            _dict['quoteMaxSignificant'] = None

        # set to None if base_scale (nullable) is None
        # and model_fields_set contains the field
        if self.base_scale is None and "base_scale" in self.model_fields_set:
            _dict['baseScale'] = None

        # set to None if quote_scale (nullable) is None
        # and model_fields_set contains the field
        if self.quote_scale is None and "quote_scale" in self.model_fields_set:
            _dict['quoteScale'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Instrument from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "instrumentId": obj.get("instrumentId"),
            "venue": obj.get("venue"),
            "symbol": obj.get("symbol"),
            "externalSymbol": obj.get("externalSymbol"),
            "description": obj.get("description"),
            "instrumentType": obj.get("instrumentType"),
            "status": obj.get("status"),
            "baseAsset": obj.get("baseAsset"),
            "quoteAsset": obj.get("quoteAsset"),
            "baseSecurityType": obj.get("baseSecurityType"),
            "quoteSecurityType": obj.get("quoteSecurityType"),
            "basePrecision": obj.get("basePrecision"),
            "quotePrecision": obj.get("quotePrecision"),
            "baseMaxSignificant": obj.get("baseMaxSignificant"),
            "quoteMaxSignificant": obj.get("quoteMaxSignificant"),
            "lotSize": obj.get("lotSize"),
            "pipSize": obj.get("pipSize"),
            "baseScale": obj.get("baseScale"),
            "quoteScale": obj.get("quoteScale"),
            "minQuantity": obj.get("minQuantity"),
            "maxQuantity": obj.get("maxQuantity"),
            "minNotional": obj.get("minNotional"),
            "maxNotional": obj.get("maxNotional"),
            "orderFilters": obj.get("orderFilters"),
            "orderTypes": obj.get("orderTypes"),
            "timeInForceOptions": obj.get("timeInForceOptions"),
            "tradingHours": obj.get("tradingHours"),
            "isIcebergAllowed": obj.get("isIcebergAllowed"),
            "icebergMinQuantity": obj.get("icebergMinQuantity"),
            "deliveryDate": obj.get("deliveryDate"),
            "deliveryDateTime": obj.get("deliveryDateTime"),
            "exerciseStyle": obj.get("exerciseStyle"),
            "strikePrice": obj.get("strikePrice")
        })
        return _obj


