# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OperationType(str, Enum):
    """
    Operation type
    """

    """
    allowed enum values
    """
    CONNECT = 'CONNECT'
    DISCONNECT = 'DISCONNECT'
    ENABLE = 'ENABLE'
    DISABLE = 'DISABLE'
    UPDATE = 'UPDATE'
    CREDENTIAL_REVOKE = 'CREDENTIAL_REVOKE'
    CREDENTIAL_ROTATE = 'CREDENTIAL_ROTATE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OperationType from a JSON string"""
        return cls(json.loads(json_str))


