# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class PortfolioSummary(BaseModel):
    """
    PortfolioSummary
    """ # noqa: E501
    trading_account_id: UUID = Field(description="UUID string", alias="tradingAccountId")
    currency: StrictStr = Field(description="Base currency for the portfolio summary")
    leverage: Optional[StrictInt] = Field(description="Leverage multiplier")
    equity: Annotated[str, Field(strict=True)] = Field(description="Decimal value as string to preserve precision")
    margin: Annotated[str, Field(strict=True)] = Field(description="Decimal value as string to preserve precision")
    margin_loan: Annotated[str, Field(strict=True)] = Field(description="Decimal value as string to preserve precision", alias="marginLoan")
    margin_usage: Annotated[str, Field(strict=True)] = Field(description="Decimal value as string to preserve precision", alias="marginUsage")
    margin_requirement: Annotated[str, Field(strict=True)] = Field(description="Decimal value as string to preserve precision", alias="marginRequirement")
    margin_level: Annotated[str, Field(strict=True)] = Field(description="Decimal value as string to preserve precision", alias="marginLevel")
    credit: Annotated[str, Field(strict=True)] = Field(description="Decimal value as string to preserve precision")
    risk_exposure: Annotated[str, Field(strict=True)] = Field(description="Decimal value as string to preserve precision", alias="riskExposure")
    max_risk_exposure: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Decimal value as string to preserve precision", alias="maxRiskExposure")
    risk_exposure_rate: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Decimal value as string to preserve precision", alias="riskExposureRate")
    __properties: ClassVar[List[str]] = ["tradingAccountId", "currency", "leverage", "equity", "margin", "marginLoan", "marginUsage", "marginRequirement", "marginLevel", "credit", "riskExposure", "maxRiskExposure", "riskExposureRate"]

    @field_validator('equity')
    def equity_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('margin')
    def margin_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('margin_loan')
    def margin_loan_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('margin_usage')
    def margin_usage_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('margin_requirement')
    def margin_requirement_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('margin_level')
    def margin_level_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('credit')
    def credit_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('risk_exposure')
    def risk_exposure_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('max_risk_exposure')
    def max_risk_exposure_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('risk_exposure_rate')
    def risk_exposure_rate_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PortfolioSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if leverage (nullable) is None
        # and model_fields_set contains the field
        if self.leverage is None and "leverage" in self.model_fields_set:
            _dict['leverage'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PortfolioSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tradingAccountId": obj.get("tradingAccountId"),
            "currency": obj.get("currency"),
            "leverage": obj.get("leverage"),
            "equity": obj.get("equity"),
            "margin": obj.get("margin"),
            "marginLoan": obj.get("marginLoan"),
            "marginUsage": obj.get("marginUsage"),
            "marginRequirement": obj.get("marginRequirement"),
            "marginLevel": obj.get("marginLevel"),
            "credit": obj.get("credit"),
            "riskExposure": obj.get("riskExposure"),
            "maxRiskExposure": obj.get("maxRiskExposure"),
            "riskExposureRate": obj.get("riskExposureRate")
        })
        return _obj


