# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from cadenza_client.models.position_status import PositionStatus
from cadenza_client.models.security_type import SecurityType
from typing import Optional, Set
from typing_extensions import Self

class PositionEntry(BaseModel):
    """
    PositionEntry
    """ # noqa: E501
    position_id: UUID = Field(description="UUID string", alias="positionId")
    security_symbol: StrictStr = Field(description="Security symbol", alias="securitySymbol")
    external_position_id: Optional[StrictStr] = Field(default=None, description="External position ID from the exchange", alias="externalPositionId")
    trading_account_id: UUID = Field(description="UUID string", alias="tradingAccountId")
    instrument_id: Optional[StrictStr] = Field(default=None, description="Instrument ID in format {VENUE}:{BASE}/{QUOTE}", alias="instrumentId")
    security_type: SecurityType = Field(alias="securityType")
    status: PositionStatus
    quantity: Annotated[str, Field(strict=True)] = Field(description="Decimal value as string to preserve precision")
    entry_price: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Decimal value as string to preserve precision", alias="entryPrice")
    exit_price: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Decimal value as string to preserve precision", alias="exitPrice")
    current_price: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Decimal value as string to preserve precision", alias="currentPrice")
    unrealized_pnl: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Decimal value as string to preserve precision", alias="unrealizedPnl")
    realized_pnl: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Decimal value as string to preserve precision", alias="realizedPnl")
    created_at: StrictInt = Field(description="Unix timestamp in milliseconds", alias="createdAt")
    created_at_date_time: Optional[datetime] = Field(default=None, description="Creation timestamp in ISO 8601 format", alias="createdAtDateTime")
    updated_at: StrictInt = Field(description="Unix timestamp in milliseconds", alias="updatedAt")
    updated_at_date_time: Optional[datetime] = Field(default=None, description="Last update timestamp in ISO 8601 format", alias="updatedAtDateTime")
    closed_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp in milliseconds", alias="closedAt")
    closed_at_date_time: Optional[datetime] = Field(default=None, description="Position closure timestamp in ISO 8601 format", alias="closedAtDateTime")
    __properties: ClassVar[List[str]] = ["positionId", "securitySymbol", "externalPositionId", "tradingAccountId", "instrumentId", "securityType", "status", "quantity", "entryPrice", "exitPrice", "currentPrice", "unrealizedPnl", "realizedPnl", "createdAt", "createdAtDateTime", "updatedAt", "updatedAtDateTime", "closedAt", "closedAtDateTime"]

    @field_validator('quantity')
    def quantity_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('entry_price')
    def entry_price_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('exit_price')
    def exit_price_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('current_price')
    def current_price_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('unrealized_pnl')
    def unrealized_pnl_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('realized_pnl')
    def realized_pnl_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PositionEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if external_position_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_position_id is None and "external_position_id" in self.model_fields_set:
            _dict['externalPositionId'] = None

        # set to None if closed_at_date_time (nullable) is None
        # and model_fields_set contains the field
        if self.closed_at_date_time is None and "closed_at_date_time" in self.model_fields_set:
            _dict['closedAtDateTime'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PositionEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "positionId": obj.get("positionId"),
            "securitySymbol": obj.get("securitySymbol"),
            "externalPositionId": obj.get("externalPositionId"),
            "tradingAccountId": obj.get("tradingAccountId"),
            "instrumentId": obj.get("instrumentId"),
            "securityType": obj.get("securityType"),
            "status": obj.get("status"),
            "quantity": obj.get("quantity"),
            "entryPrice": obj.get("entryPrice"),
            "exitPrice": obj.get("exitPrice"),
            "currentPrice": obj.get("currentPrice"),
            "unrealizedPnl": obj.get("unrealizedPnl"),
            "realizedPnl": obj.get("realizedPnl"),
            "createdAt": obj.get("createdAt"),
            "createdAtDateTime": obj.get("createdAtDateTime"),
            "updatedAt": obj.get("updatedAt"),
            "updatedAtDateTime": obj.get("updatedAtDateTime"),
            "closedAt": obj.get("closedAt"),
            "closedAtDateTime": obj.get("closedAtDateTime")
        })
        return _obj


