# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class QuantityRounding(str, Enum):
    """
    Quantity rounding strategy to meet lot size requirements. Empty string means no rounding (rejects orders that don't meet lot size requirements).
    """

    """
    allowed enum values
    """
    EMPTY = ''
    UP = 'UP'
    DOWN = 'DOWN'
    NEAREST = 'NEAREST'
    CEIL = 'CEIL'
    FLOOR = 'FLOOR'
    HALF_UP = 'HALF_UP'
    HALF_DOWN = 'HALF_DOWN'
    HALF_EVEN = 'HALF_EVEN'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of QuantityRounding from a JSON string"""
        return cls(json.loads(json_str))


