# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RpcMethod(str, Enum):
    """
    RPC method name corresponding to event types in the system. Format: `{category}.{resource}.{action}` - `command.*` - Actions that modify state - `query.*` - Actions that read state - `response.*` - Server responses (used internally) - `event.*` - Push notifications for state changes 
    """

    """
    allowed enum values
    """
    QUERY_DOT_SYSTEM_DOT_INFO = 'query.system.info'
    RESPONSE_DOT_SYSTEM_DOT_INFO = 'response.system.info'
    QUERY_DOT_SYSTEM_DOT_CHECK = 'query.system.check'
    RESPONSE_DOT_SYSTEM_DOT_CHECK = 'response.system.check'
    COMMAND_DOT_TRADING_ACCOUNT_DOT_CREATE = 'command.trading_account.create'
    RESPONSE_DOT_TRADING_ACCOUNT_DOT_CREATE = 'response.trading_account.create'
    COMMAND_DOT_TRADING_ACCOUNT_DOT_SAVE = 'command.trading_account.save'
    RESPONSE_DOT_TRADING_ACCOUNT_DOT_SAVE = 'response.trading_account.save'
    COMMAND_DOT_TRADING_ACCOUNT_DOT_DELETE = 'command.trading_account.delete'
    RESPONSE_DOT_TRADING_ACCOUNT_DOT_DELETE = 'response.trading_account.delete'
    COMMAND_DOT_TRADING_ACCOUNT_DOT_UPDATE = 'command.trading_account.update'
    RESPONSE_DOT_TRADING_ACCOUNT_DOT_UPDATE = 'response.trading_account.update'
    COMMAND_DOT_TRADING_ACCOUNT_DOT_VALIDATE = 'command.trading_account.validate'
    RESPONSE_DOT_TRADING_ACCOUNT_DOT_VALIDATE = 'response.trading_account.validate'
    COMMAND_DOT_TRADING_ACCOUNT_DOT_CONNECT = 'command.trading_account.connect'
    RESPONSE_DOT_TRADING_ACCOUNT_DOT_CONNECT = 'response.trading_account.connect'
    COMMAND_DOT_TRADING_ACCOUNT_DOT_DISCONNECT = 'command.trading_account.disconnect'
    RESPONSE_DOT_TRADING_ACCOUNT_DOT_DISCONNECT = 'response.trading_account.disconnect'
    COMMAND_DOT_TRADING_ACCOUNT_DOT_ENABLE = 'command.trading_account.enable'
    RESPONSE_DOT_TRADING_ACCOUNT_DOT_ENABLE = 'response.trading_account.enable'
    COMMAND_DOT_TRADING_ACCOUNT_DOT_DISABLE = 'command.trading_account.disable'
    RESPONSE_DOT_TRADING_ACCOUNT_DOT_DISABLE = 'response.trading_account.disable'
    QUERY_DOT_TRADING_ACCOUNT_DOT_LIST = 'query.trading_account.list'
    RESPONSE_DOT_TRADING_ACCOUNT_DOT_LIST = 'response.trading_account.list'
    QUERY_DOT_TRADING_ACCOUNT_DOT_OPERATION_DOT_LIST = 'query.trading_account.operation.list'
    RESPONSE_DOT_TRADING_ACCOUNT_DOT_OPERATION_DOT_LIST = 'response.trading_account.operation.list'
    EVENT_DOT_TRADING_ACCOUNT_DOT_UPDATED = 'event.trading_account.updated'
    EVENT_DOT_TRADING_ACCOUNT_DOT_SUBSCRIPTION_DOT_UPDATED = 'event.trading_account.subscription.updated'
    COMMAND_DOT_TRADING_ACCOUNT_DOT_SUBSCRIBE = 'command.trading_account.subscribe'
    RESPONSE_DOT_TRADING_ACCOUNT_DOT_SUBSCRIBE = 'response.trading_account.subscribe'
    COMMAND_DOT_TRADING_ACCOUNT_DOT_UNSUBSCRIBE = 'command.trading_account.unsubscribe'
    RESPONSE_DOT_TRADING_ACCOUNT_DOT_UNSUBSCRIBE = 'response.trading_account.unsubscribe'
    QUERY_DOT_TRADING_ACCOUNT_DOT_SUBSCRIPTION_DOT_LIST = 'query.trading_account.subscription.list'
    RESPONSE_DOT_TRADING_ACCOUNT_DOT_SUBSCRIPTION_DOT_LIST = 'response.trading_account.subscription.list'
    COMMAND_DOT_CREDENTIAL_DOT_CREATE = 'command.credential.create'
    RESPONSE_DOT_CREDENTIAL_DOT_CREATE = 'response.credential.create'
    COMMAND_DOT_CREDENTIAL_DOT_SAVE = 'command.credential.save'
    RESPONSE_DOT_CREDENTIAL_DOT_SAVE = 'response.credential.save'
    QUERY_DOT_CREDENTIAL_DOT_LIST = 'query.credential.list'
    RESPONSE_DOT_CREDENTIAL_DOT_LIST = 'response.credential.list'
    COMMAND_DOT_CREDENTIAL_DOT_REVOKE = 'command.credential.revoke'
    RESPONSE_DOT_CREDENTIAL_DOT_REVOKE = 'response.credential.revoke'
    COMMAND_DOT_CREDENTIAL_DOT_ROTATE = 'command.credential.rotate'
    RESPONSE_DOT_CREDENTIAL_DOT_ROTATE = 'response.credential.rotate'
    COMMAND_DOT_CREDENTIAL_DOT_VERIFY = 'command.credential.verify'
    RESPONSE_DOT_CREDENTIAL_DOT_VERIFY = 'response.credential.verify'
    EVENT_DOT_CREDENTIAL_DOT_UPDATED = 'event.credential.updated'
    COMMAND_DOT_TRADE_ORDER_DOT_SUBMIT = 'command.trade_order.submit'
    RESPONSE_DOT_TRADE_ORDER_DOT_SUBMIT = 'response.trade_order.submit'
    COMMAND_DOT_TRADE_ORDER_DOT_CANCEL = 'command.trade_order.cancel'
    RESPONSE_DOT_TRADE_ORDER_DOT_CANCEL = 'response.trade_order.cancel'
    COMMAND_DOT_TRADE_ORDER_DOT_SAVE = 'command.trade_order.save'
    RESPONSE_DOT_TRADE_ORDER_DOT_SAVE = 'response.trade_order.save'
    QUERY_DOT_TRADE_ORDER_DOT_GET = 'query.trade_order.get'
    RESPONSE_DOT_TRADE_ORDER_DOT_GET = 'response.trade_order.get'
    QUERY_DOT_TRADE_ORDER_DOT_GET_BY_ID = 'query.trade_order.get_by_id'
    RESPONSE_DOT_TRADE_ORDER_DOT_GET_BY_ID = 'response.trade_order.get_by_id'
    QUERY_DOT_TRADE_ORDER_DOT_LIST = 'query.trade_order.list'
    RESPONSE_DOT_TRADE_ORDER_DOT_LIST = 'response.trade_order.list'
    EVENT_DOT_TRADE_ORDER_DOT_UPDATED = 'event.trade_order.updated'
    QUERY_DOT_PORTFOLIO_DOT_GET = 'query.portfolio.get'
    RESPONSE_DOT_PORTFOLIO_DOT_GET = 'response.portfolio.get'
    QUERY_DOT_PORTFOLIO_DOT_LIST = 'query.portfolio.list'
    RESPONSE_DOT_PORTFOLIO_DOT_LIST = 'response.portfolio.list'
    COMMAND_DOT_PORTFOLIO_DOT_SAVE = 'command.portfolio.save'
    RESPONSE_DOT_PORTFOLIO_DOT_SAVE = 'response.portfolio.save'
    EVENT_DOT_PORTFOLIO_DOT_UPDATED = 'event.portfolio.updated'
    COMMAND_DOT_INSTRUMENT_DOT_SYNC = 'command.instrument.sync'
    RESPONSE_DOT_INSTRUMENT_DOT_SYNC = 'response.instrument.sync'
    COMMAND_DOT_INSTRUMENT_DOT_SAVE = 'command.instrument.save'
    RESPONSE_DOT_INSTRUMENT_DOT_SAVE = 'response.instrument.save'
    QUERY_DOT_INSTRUMENT_DOT_LIST = 'query.instrument.list'
    RESPONSE_DOT_INSTRUMENT_DOT_LIST = 'response.instrument.list'
    COMMAND_DOT_INSTRUMENT_DOT_DELETE = 'command.instrument.delete'
    RESPONSE_DOT_INSTRUMENT_DOT_DELETE = 'response.instrument.delete'
    COMMAND_DOT_INSTRUMENT_DOT_ENABLE = 'command.instrument.enable'
    RESPONSE_DOT_INSTRUMENT_DOT_ENABLE = 'response.instrument.enable'
    COMMAND_DOT_INSTRUMENT_DOT_DISABLE = 'command.instrument.disable'
    RESPONSE_DOT_INSTRUMENT_DOT_DISABLE = 'response.instrument.disable'
    EVENT_DOT_INSTRUMENT_DOT_UPDATED = 'event.instrument.updated'
    COMMAND_DOT_SECURITY_DOT_SYNC = 'command.security.sync'
    RESPONSE_DOT_SECURITY_DOT_SYNC = 'response.security.sync'
    COMMAND_DOT_SECURITY_DOT_SAVE = 'command.security.save'
    RESPONSE_DOT_SECURITY_DOT_SAVE = 'response.security.save'
    COMMAND_DOT_SECURITY_DOT_DELETE = 'command.security.delete'
    RESPONSE_DOT_SECURITY_DOT_DELETE = 'response.security.delete'
    QUERY_DOT_SECURITY_DOT_LIST = 'query.security.list'
    RESPONSE_DOT_SECURITY_DOT_LIST = 'response.security.list'
    EVENT_DOT_SECURITY_DOT_UPDATED = 'event.security.updated'
    QUERY_DOT_VENUE_DOT_LIST = 'query.venue.list'
    RESPONSE_DOT_VENUE_DOT_LIST = 'response.venue.list'
    QUERY_DOT_ORDERBOOK_DOT_GET = 'query.orderbook.get'
    RESPONSE_DOT_ORDERBOOK_DOT_GET = 'response.orderbook.get'
    QUERY_DOT_ORDERBOOK_DOT_LIST = 'query.orderbook.list'
    RESPONSE_DOT_ORDERBOOK_DOT_LIST = 'response.orderbook.list'
    COMMAND_DOT_ORDERBOOK_DOT_SAVE = 'command.orderbook.save'
    RESPONSE_DOT_ORDERBOOK_DOT_SAVE = 'response.orderbook.save'
    EVENT_DOT_ORDERBOOK_DOT_UPDATED = 'event.orderbook.updated'
    COMMAND_DOT_KLINE_DOT_SAVE = 'command.kline.save'
    RESPONSE_DOT_KLINE_DOT_SAVE = 'response.kline.save'
    QUERY_DOT_KLINE_DOT_LIST = 'query.kline.list'
    RESPONSE_DOT_KLINE_DOT_LIST = 'response.kline.list'
    COMMAND_DOT_TICKER_DOT_SAVE = 'command.ticker.save'
    RESPONSE_DOT_TICKER_DOT_SAVE = 'response.ticker.save'
    QUERY_DOT_TICKER_DOT_LIST = 'query.ticker.list'
    RESPONSE_DOT_TICKER_DOT_LIST = 'response.ticker.list'
    COMMAND_DOT_MARKET_DOT_SUBSCRIPTION_DOT_ORDERBOOK_DOT_SUBSCRIBE = 'command.market.subscription.orderbook.subscribe'
    RESPONSE_DOT_MARKET_DOT_SUBSCRIPTION_DOT_ORDERBOOK_DOT_SUBSCRIBE = 'response.market.subscription.orderbook.subscribe'
    COMMAND_DOT_MARKET_DOT_SUBSCRIPTION_DOT_ORDERBOOK_DOT_UNSUBSCRIBE = 'command.market.subscription.orderbook.unsubscribe'
    RESPONSE_DOT_MARKET_DOT_SUBSCRIPTION_DOT_ORDERBOOK_DOT_UNSUBSCRIBE = 'response.market.subscription.orderbook.unsubscribe'
    QUERY_DOT_MARKET_DOT_SUBSCRIPTION_DOT_ORDERBOOK_DOT_LIST = 'query.market.subscription.orderbook.list'
    RESPONSE_DOT_MARKET_DOT_SUBSCRIPTION_DOT_ORDERBOOK_DOT_LIST = 'response.market.subscription.orderbook.list'
    COMMAND_DOT_SUBSCRIPTION_DOT_CREATE = 'command.subscription.create'
    RESPONSE_DOT_SUBSCRIPTION_DOT_CREATE = 'response.subscription.create'
    QUERY_DOT_SUBSCRIPTION_DOT_LIST = 'query.subscription.list'
    RESPONSE_DOT_SUBSCRIPTION_DOT_LIST = 'response.subscription.list'
    EVENT_DOT_SUBSCRIPTION_DOT_UPDATED = 'event.subscription.updated'
    COMMAND_DOT_SUBSCRIPTION_DOT_MC_DOT_CREATE = 'command.subscription.mc.create'
    RESPONSE_DOT_SUBSCRIPTION_DOT_MC_DOT_CREATE = 'response.subscription.mc.create'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RpcMethod from a JSON string"""
        return cls(json.loads(json_str))


