# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from cadenza_client.models.credential_status import CredentialStatus
from cadenza_client.models.credential_type import CredentialType
from cadenza_client.models.venue import Venue
from typing import Optional, Set
from typing_extensions import Self

class RpcTradingAccountCredential(BaseModel):
    """
    Trading account credential
    """ # noqa: E501
    credential_id: Optional[UUID] = Field(default=None, alias="credentialId")
    nickname: Optional[StrictStr] = None
    credential_type: Optional[CredentialType] = Field(default=None, alias="credentialType")
    status: Optional[CredentialStatus] = None
    venue: Optional[Venue] = None
    api_key: Optional[StrictStr] = Field(default=None, description="API key (only in responses where withSecret=true)", alias="apiKey")
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    revoked_at: Optional[datetime] = Field(default=None, alias="revokedAt")
    with_info: Optional[StrictBool] = Field(default=None, description="Whether metadata fields are populated", alias="withInfo")
    with_secret: Optional[StrictBool] = Field(default=None, description="Whether secret fields are populated", alias="withSecret")
    __properties: ClassVar[List[str]] = ["credentialId", "nickname", "credentialType", "status", "venue", "apiKey", "createdAt", "updatedAt", "revokedAt", "withInfo", "withSecret"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RpcTradingAccountCredential from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RpcTradingAccountCredential from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "credentialId": obj.get("credentialId"),
            "nickname": obj.get("nickname"),
            "credentialType": obj.get("credentialType"),
            "status": obj.get("status"),
            "venue": obj.get("venue"),
            "apiKey": obj.get("apiKey"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "revokedAt": obj.get("revokedAt"),
            "withInfo": obj.get("withInfo"),
            "withSecret": obj.get("withSecret")
        })
        return _obj


