# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from cadenza_client.models.order_side import OrderSide
from cadenza_client.models.order_status import OrderStatus
from cadenza_client.models.order_type import OrderType
from cadenza_client.models.quantity_rounding import QuantityRounding
from cadenza_client.models.quantity_type import QuantityType
from cadenza_client.models.rpc_security_quantity import RpcSecurityQuantity
from cadenza_client.models.time_in_force import TimeInForce
from typing import Optional, Set
from typing_extensions import Self

class RpcTradeOrder(BaseModel):
    """
    Trade order model
    """ # noqa: E501
    trade_order_id: Optional[UUID] = Field(default=None, description="Unique trade order ID", alias="tradeOrderId")
    client_order_id: Optional[StrictStr] = Field(default=None, description="Client-assigned order ID", alias="clientOrderId")
    original_client_order_id: Optional[StrictStr] = Field(default=None, description="Original client order ID (for cancel/replace)", alias="originalClientOrderId")
    external_order_id: Optional[StrictStr] = Field(default=None, description="Order ID from external venue", alias="externalOrderId")
    idempotency_key: Optional[StrictStr] = Field(default=None, description="Idempotency key", alias="idempotencyKey")
    venue: Optional[StrictStr] = Field(default=None, description="Trading venue")
    trading_account_id: Optional[UUID] = Field(default=None, description="Trading account ID", alias="tradingAccountId")
    external_trading_account_id: Optional[StrictStr] = Field(default=None, description="External account ID at venue", alias="externalTradingAccountId")
    instrument_id: Optional[StrictStr] = Field(default=None, description="Instrument ID (VENUE:BASE/QUOTE)", alias="instrumentId")
    external_symbol: Optional[StrictStr] = Field(default=None, description="Symbol at external venue", alias="externalSymbol")
    base_asset: Optional[StrictStr] = Field(default=None, description="Base asset", alias="baseAsset")
    quote_asset: Optional[StrictStr] = Field(default=None, description="Quote asset", alias="quoteAsset")
    order_type: Optional[OrderType] = Field(default=None, alias="orderType")
    order_side: Optional[OrderSide] = Field(default=None, alias="orderSide")
    quantity_type: Optional[QuantityType] = Field(default=None, alias="quantityType")
    quantity: Optional[StrictStr] = Field(default=None, description="Order quantity (decimal string)")
    quote_currency_quantity: Optional[StrictStr] = Field(default=None, description="Quantity in quote currency", alias="quoteCurrencyQuantity")
    position_percentage: Optional[StrictStr] = Field(default=None, description="Quantity as position percentage", alias="positionPercentage")
    quantity_rounding: Optional[QuantityRounding] = Field(default=QuantityRounding.EMPTY, alias="quantityRounding")
    limit_price: Optional[StrictStr] = Field(default=None, description="Limit price (decimal string)", alias="limitPrice")
    stop_price: Optional[StrictStr] = Field(default=None, description="Stop price (decimal string)", alias="stopPrice")
    time_in_force: Optional[TimeInForce] = Field(default=None, alias="timeInForce")
    status: Optional[OrderStatus] = None
    executed_price: Optional[StrictStr] = Field(default=None, description="Average executed price", alias="executedPrice")
    executed_percentage: Optional[StrictStr] = Field(default=None, description="Percentage of order filled", alias="executedPercentage")
    executed_quantity: Optional[StrictStr] = Field(default=None, description="Quantity executed", alias="executedQuantity")
    executed_cost: Optional[StrictStr] = Field(default=None, description="Total cost in quote currency", alias="executedCost")
    fees: Optional[List[RpcSecurityQuantity]] = Field(default=None, description="Fees charged")
    cancel_reason: Optional[StrictStr] = Field(default=None, description="Reason for cancellation", alias="cancelReason")
    reject_reason: Optional[StrictStr] = Field(default=None, description="Reason for rejection", alias="rejectReason")
    created_at: Optional[datetime] = Field(default=None, description="Order creation time", alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, description="Last update time", alias="updatedAt")
    expire_at: Optional[datetime] = Field(default=None, description="Order expiration time (for GTD)", alias="expireAt")
    last_execution_at: Optional[datetime] = Field(default=None, description="Time of last execution", alias="lastExecutionAt")
    canceled_at: Optional[datetime] = Field(default=None, description="Time of cancellation", alias="canceledAt")
    __properties: ClassVar[List[str]] = ["tradeOrderId", "clientOrderId", "originalClientOrderId", "externalOrderId", "idempotencyKey", "venue", "tradingAccountId", "externalTradingAccountId", "instrumentId", "externalSymbol", "baseAsset", "quoteAsset", "orderType", "orderSide", "quantityType", "quantity", "quoteCurrencyQuantity", "positionPercentage", "quantityRounding", "limitPrice", "stopPrice", "timeInForce", "status", "executedPrice", "executedPercentage", "executedQuantity", "executedCost", "fees", "cancelReason", "rejectReason", "createdAt", "updatedAt", "expireAt", "lastExecutionAt", "canceledAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RpcTradeOrder from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in fees (list)
        _items = []
        if self.fees:
            for _item_fees in self.fees:
                if _item_fees:
                    _items.append(_item_fees.to_dict())
            _dict['fees'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RpcTradeOrder from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tradeOrderId": obj.get("tradeOrderId"),
            "clientOrderId": obj.get("clientOrderId"),
            "originalClientOrderId": obj.get("originalClientOrderId"),
            "externalOrderId": obj.get("externalOrderId"),
            "idempotencyKey": obj.get("idempotencyKey"),
            "venue": obj.get("venue"),
            "tradingAccountId": obj.get("tradingAccountId"),
            "externalTradingAccountId": obj.get("externalTradingAccountId"),
            "instrumentId": obj.get("instrumentId"),
            "externalSymbol": obj.get("externalSymbol"),
            "baseAsset": obj.get("baseAsset"),
            "quoteAsset": obj.get("quoteAsset"),
            "orderType": obj.get("orderType"),
            "orderSide": obj.get("orderSide"),
            "quantityType": obj.get("quantityType"),
            "quantity": obj.get("quantity"),
            "quoteCurrencyQuantity": obj.get("quoteCurrencyQuantity"),
            "positionPercentage": obj.get("positionPercentage"),
            "quantityRounding": obj.get("quantityRounding") if obj.get("quantityRounding") is not None else QuantityRounding.EMPTY,
            "limitPrice": obj.get("limitPrice"),
            "stopPrice": obj.get("stopPrice"),
            "timeInForce": obj.get("timeInForce"),
            "status": obj.get("status"),
            "executedPrice": obj.get("executedPrice"),
            "executedPercentage": obj.get("executedPercentage"),
            "executedQuantity": obj.get("executedQuantity"),
            "executedCost": obj.get("executedCost"),
            "fees": [RpcSecurityQuantity.from_dict(_item) for _item in obj["fees"]] if obj.get("fees") is not None else None,
            "cancelReason": obj.get("cancelReason"),
            "rejectReason": obj.get("rejectReason"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "expireAt": obj.get("expireAt"),
            "lastExecutionAt": obj.get("lastExecutionAt"),
            "canceledAt": obj.get("canceledAt")
        })
        return _obj


