# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ServiceName(str, Enum):
    """
    Service name identifier
    """

    """
    allowed enum values
    """
    TRADE_ORDER_SERVICE = 'TRADE_ORDER_SERVICE'
    TRADING_ACCOUNT_SERVICE = 'TRADING_ACCOUNT_SERVICE'
    MARKET_SERVICE = 'MARKET_SERVICE'
    PORTFOLIO_SERVICE = 'PORTFOLIO_SERVICE'
    EXECUTION_ENGINE = 'EXECUTION_ENGINE'
    HTTP_SERVER = 'HTTP_SERVER'
    MARKET_QUERY = 'MARKET_QUERY'
    MARKET_REALTIME = 'MARKET_REALTIME'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ServiceName from a JSON string"""
        return cls(json.loads(json_str))


