# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SubscriptionType(str, Enum):
    """
    Type of data subscription
    """

    """
    allowed enum values
    """
    MARKET_DOT_SUBSCRIPTION_DOT_ORDERBOOK = 'MARKET.SUBSCRIPTION.ORDERBOOK'
    MARKET_DOT_SUBSCRIPTION_DOT_TRADE = 'MARKET.SUBSCRIPTION.TRADE'
    MARKET_DOT_SUBSCRIPTION_DOT_TICKER = 'MARKET.SUBSCRIPTION.TICKER'
    MARKET_DOT_SUBSCRIPTION_DOT_KLINE = 'MARKET.SUBSCRIPTION.KLINE'
    TRADING_ACCOUNT_DOT_SUBSCRIPTION_DOT_USER_DATA = 'TRADING_ACCOUNT.SUBSCRIPTION.USER_DATA'
    TRADING_ACCOUNT_DOT_SUBSCRIPTION_DOT_PORTFOLIO = 'TRADING_ACCOUNT.SUBSCRIPTION.PORTFOLIO'
    TRADING_ACCOUNT_DOT_SUBSCRIPTION_DOT_EXECUTION_REPORT = 'TRADING_ACCOUNT.SUBSCRIPTION.EXECUTION_REPORT'
    TRADING_ACCOUNT_DOT_SUBSCRIPTION_DOT_TRADING_ACCOUNT = 'TRADING_ACCOUNT.SUBSCRIPTION.TRADING_ACCOUNT'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SubscriptionType from a JSON string"""
        return cls(json.loads(json_str))


