# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from cadenza_client.models.credential_type import CredentialType
from cadenza_client.models.trading_account_credential_status import TradingAccountCredentialStatus
from cadenza_client.models.venue import Venue
from typing import Optional, Set
from typing_extensions import Self

class TradingAccountCredential(BaseModel):
    """
    TradingAccountCredential
    """ # noqa: E501
    credential_id: UUID = Field(description="UUID string", alias="credentialId")
    venue: Venue
    credential_type: CredentialType = Field(alias="credentialType")
    nickname: Optional[StrictStr] = None
    status: TradingAccountCredentialStatus
    created_at: StrictInt = Field(description="Unix timestamp in milliseconds", alias="createdAt")
    created_at_date_time: Optional[datetime] = Field(default=None, description="Creation timestamp in ISO 8601 format", alias="createdAtDateTime")
    updated_at: StrictInt = Field(description="Unix timestamp in milliseconds", alias="updatedAt")
    updated_at_date_time: Optional[datetime] = Field(default=None, description="Last update timestamp in ISO 8601 format", alias="updatedAtDateTime")
    revoked_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp in milliseconds", alias="revokedAt")
    revoked_at_date_time: Optional[datetime] = Field(default=None, description="Revocation timestamp in ISO 8601 format", alias="revokedAtDateTime")
    __properties: ClassVar[List[str]] = ["credentialId", "venue", "credentialType", "nickname", "status", "createdAt", "createdAtDateTime", "updatedAt", "updatedAtDateTime", "revokedAt", "revokedAtDateTime"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TradingAccountCredential from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TradingAccountCredential from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "credentialId": obj.get("credentialId"),
            "venue": obj.get("venue"),
            "credentialType": obj.get("credentialType"),
            "nickname": obj.get("nickname"),
            "status": obj.get("status"),
            "createdAt": obj.get("createdAt"),
            "createdAtDateTime": obj.get("createdAtDateTime"),
            "updatedAt": obj.get("updatedAt"),
            "updatedAtDateTime": obj.get("updatedAtDateTime"),
            "revokedAt": obj.get("revokedAt"),
            "revokedAtDateTime": obj.get("revokedAtDateTime")
        })
        return _obj


