# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from cadenza_client.models.order_quantity_type import OrderQuantityType
from cadenza_client.models.order_side import OrderSide
from cadenza_client.models.order_status import OrderStatus
from cadenza_client.models.order_type import OrderType
from cadenza_client.models.quantity_rounding import QuantityRounding
from cadenza_client.models.security_quantity import SecurityQuantity
from cadenza_client.models.time_in_force import TimeInForce
from cadenza_client.models.trade_execution import TradeExecution
from cadenza_client.models.venue import Venue
from typing import Optional, Set
from typing_extensions import Self

class TradeOrder(BaseModel):
    """
    TradeOrder
    """ # noqa: E501
    trade_order_id: UUID = Field(description="UUID string", alias="tradeOrderId")
    order_list_id: Optional[StrictStr] = Field(default=None, description="Exchange order list ID linking OCO/OTO/OTOCO legs. For OCO parents, externalOrderId uses 'ol_' prefix.", alias="orderListId")
    trading_account_id: UUID = Field(description="UUID string", alias="tradingAccountId")
    venue: Venue
    position_id: Optional[UUID] = Field(default=None, description="UUID string", alias="positionId")
    instrument_id: StrictStr = Field(description="Instrument ID in format {VENUE}:{BASE}/{QUOTE}", alias="instrumentId")
    quote_id: Optional[UUID] = Field(default=None, description="UUID string", alias="quoteId")
    base_asset: StrictStr = Field(description="Base asset in the trading pair", alias="baseAsset")
    quote_asset: StrictStr = Field(description="Quote asset in the trading pair", alias="quoteAsset")
    order_side: OrderSide = Field(alias="orderSide")
    order_type: OrderType = Field(alias="orderType")
    time_in_force: TimeInForce = Field(alias="timeInForce")
    status: OrderStatus
    reject_reason: Optional[StrictStr] = Field(default=None, description="Reason for order rejection", alias="rejectReason")
    cancel_reason: Optional[StrictStr] = Field(default=None, description="Reason for order cancellation", alias="cancelReason")
    limit_price: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Decimal value as string to preserve precision", alias="limitPrice")
    stop_price: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Decimal value as string to preserve precision", alias="stopPrice")
    take_profit_price: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Decimal value as string to preserve precision", alias="takeProfitPrice")
    take_profit_limit_price: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Decimal value as string to preserve precision", alias="takeProfitLimitPrice")
    stop_loss_price: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Decimal value as string to preserve precision", alias="stopLossPrice")
    stop_loss_limit_price: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Decimal value as string to preserve precision", alias="stopLossLimitPrice")
    take_profit_time_in_force: Optional[TimeInForce] = Field(default=None, alias="takeProfitTimeInForce")
    stop_loss_time_in_force: Optional[TimeInForce] = Field(default=None, alias="stopLossTimeInForce")
    quantity: Annotated[str, Field(strict=True)] = Field(description="Decimal value as string to preserve precision")
    order_quantity_type: OrderQuantityType = Field(alias="orderQuantityType")
    quantity_rounding: Optional[QuantityRounding] = Field(default=QuantityRounding.EMPTY, alias="quantityRounding")
    executed_price: Annotated[str, Field(strict=True)] = Field(description="Decimal value as string to preserve precision", alias="executedPrice")
    executed_quantity: Annotated[str, Field(strict=True)] = Field(description="Decimal value as string to preserve precision", alias="executedQuantity")
    executed_cost: Annotated[str, Field(strict=True)] = Field(description="Decimal value as string to preserve precision", alias="executedCost")
    fees: List[SecurityQuantity] = Field(description="Aggregated fees across all executions")
    executions: Optional[List[TradeExecution]] = Field(default=None, description="Detailed breakdown of executions across different venues")
    created_at: StrictInt = Field(description="Unix timestamp in milliseconds", alias="createdAt")
    created_at_date_time: Optional[datetime] = Field(default=None, description="Creation timestamp in ISO 8601 format", alias="createdAtDateTime")
    updated_at: StrictInt = Field(description="Unix timestamp in milliseconds", alias="updatedAt")
    updated_at_date_time: Optional[datetime] = Field(default=None, description="Last update timestamp in ISO 8601 format", alias="updatedAtDateTime")
    expire_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp in milliseconds", alias="expireAt")
    expire_at_date_time: Optional[datetime] = Field(default=None, description="Expiration timestamp in ISO 8601 format", alias="expireAtDateTime")
    canceled_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp in milliseconds", alias="canceledAt")
    canceled_at_date_time: Optional[datetime] = Field(default=None, description="Cancellation timestamp in ISO 8601 format", alias="canceledAtDateTime")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["tradeOrderId", "orderListId", "tradingAccountId", "venue", "positionId", "instrumentId", "quoteId", "baseAsset", "quoteAsset", "orderSide", "orderType", "timeInForce", "status", "rejectReason", "cancelReason", "limitPrice", "stopPrice", "takeProfitPrice", "takeProfitLimitPrice", "stopLossPrice", "stopLossLimitPrice", "takeProfitTimeInForce", "stopLossTimeInForce", "quantity", "orderQuantityType", "quantityRounding", "executedPrice", "executedQuantity", "executedCost", "fees", "executions", "createdAt", "createdAtDateTime", "updatedAt", "updatedAtDateTime", "expireAt", "expireAtDateTime", "canceledAt", "canceledAtDateTime"]

    @field_validator('limit_price')
    def limit_price_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('stop_price')
    def stop_price_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('take_profit_price')
    def take_profit_price_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('take_profit_limit_price')
    def take_profit_limit_price_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('stop_loss_price')
    def stop_loss_price_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('stop_loss_limit_price')
    def stop_loss_limit_price_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('quantity')
    def quantity_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('executed_price')
    def executed_price_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('executed_quantity')
    def executed_quantity_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('executed_cost')
    def executed_cost_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TradeOrder from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in fees (list)
        _items = []
        if self.fees:
            for _item_fees in self.fees:
                if _item_fees:
                    _items.append(_item_fees.to_dict())
            _dict['fees'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in executions (list)
        _items = []
        if self.executions:
            for _item_executions in self.executions:
                if _item_executions:
                    _items.append(_item_executions.to_dict())
            _dict['executions'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TradeOrder from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tradeOrderId": obj.get("tradeOrderId"),
            "orderListId": obj.get("orderListId"),
            "tradingAccountId": obj.get("tradingAccountId"),
            "venue": obj.get("venue"),
            "positionId": obj.get("positionId"),
            "instrumentId": obj.get("instrumentId"),
            "quoteId": obj.get("quoteId"),
            "baseAsset": obj.get("baseAsset"),
            "quoteAsset": obj.get("quoteAsset"),
            "orderSide": obj.get("orderSide"),
            "orderType": obj.get("orderType"),
            "timeInForce": obj.get("timeInForce"),
            "status": obj.get("status"),
            "rejectReason": obj.get("rejectReason"),
            "cancelReason": obj.get("cancelReason"),
            "limitPrice": obj.get("limitPrice"),
            "stopPrice": obj.get("stopPrice"),
            "takeProfitPrice": obj.get("takeProfitPrice"),
            "takeProfitLimitPrice": obj.get("takeProfitLimitPrice"),
            "stopLossPrice": obj.get("stopLossPrice"),
            "stopLossLimitPrice": obj.get("stopLossLimitPrice"),
            "takeProfitTimeInForce": obj.get("takeProfitTimeInForce"),
            "stopLossTimeInForce": obj.get("stopLossTimeInForce"),
            "quantity": obj.get("quantity"),
            "orderQuantityType": obj.get("orderQuantityType"),
            "quantityRounding": obj.get("quantityRounding") if obj.get("quantityRounding") is not None else QuantityRounding.EMPTY,
            "executedPrice": obj.get("executedPrice"),
            "executedQuantity": obj.get("executedQuantity"),
            "executedCost": obj.get("executedCost"),
            "fees": [SecurityQuantity.from_dict(_item) for _item in obj["fees"]] if obj.get("fees") is not None else None,
            "executions": [TradeExecution.from_dict(_item) for _item in obj["executions"]] if obj.get("executions") is not None else None,
            "createdAt": obj.get("createdAt"),
            "createdAtDateTime": obj.get("createdAtDateTime"),
            "updatedAt": obj.get("updatedAt"),
            "updatedAtDateTime": obj.get("updatedAtDateTime"),
            "expireAt": obj.get("expireAt"),
            "expireAtDateTime": obj.get("expireAtDateTime"),
            "canceledAt": obj.get("canceledAt"),
            "canceledAtDateTime": obj.get("canceledAtDateTime")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


