# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Venue(str, Enum):
    """
    Trading venue identifier. UAT/sandbox environments are treated as separate venues. Note: _SANDBOX and _PAPER suffixes are deprecated. Use _UAT suffix for new integrations. 
    """

    """
    allowed enum values
    """
    EMPTY = ''
    BINANCE = 'BINANCE'
    B2C2 = 'B2C2'
    WINTERMUTE = 'WINTERMUTE'
    BLOCKFILLS = 'BLOCKFILLS'
    STONEX = 'STONEX'
    CUMBERLAND = 'CUMBERLAND'
    IBKR = 'IBKR'
    DERIBIT = 'DERIBIT'
    BITFINEX = 'BITFINEX'
    OKX = 'OKX'
    BINANCE_UAT = 'BINANCE_UAT'
    B2_C2_UAT = 'B2C2_UAT'
    WINTERMUTE_UAT = 'WINTERMUTE_UAT'
    BLOCKFILLS_UAT = 'BLOCKFILLS_UAT'
    STONEX_UAT = 'STONEX_UAT'
    CUMBERLAND_UAT = 'CUMBERLAND_UAT'
    IBKR_UAT = 'IBKR_UAT'
    DERIBIT_UAT = 'DERIBIT_UAT'
    BITFINEX_UAT = 'BITFINEX_UAT'
    OKX_UAT = 'OKX_UAT'
    BINANCE_SANDBOX = 'BINANCE_SANDBOX'
    B2_C2_SANDBOX = 'B2C2_SANDBOX'
    IBKR_PAPER = 'IBKR_PAPER'
    MOCK = 'MOCK'
    PAPER = 'PAPER'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Venue from a JSON string"""
        return cls(json.loads(json_str))


