# coding: utf-8

"""
    Algo724 Cadenza Fermata API

    OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>

    The version of the OpenAPI document: 3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cadenza_client.models.ws_connect_push import WsConnectPush
from cadenza_client.models.ws_disconnect import WsDisconnect
from cadenza_client.models.ws_join import WsJoin
from cadenza_client.models.ws_leave import WsLeave
from cadenza_client.models.ws_message import WsMessage
from cadenza_client.models.ws_publication import WsPublication
from cadenza_client.models.ws_refresh_push import WsRefreshPush
from cadenza_client.models.ws_subscribe_push import WsSubscribePush
from cadenza_client.models.ws_unsubscribe_push import WsUnsubscribePush
from typing import Optional, Set
from typing_extensions import Self

class WsPush(BaseModel):
    """
    Server push message (asynchronous, id=0 in reply)
    """ # noqa: E501
    channel: Optional[StrictStr] = Field(default=None, description="Channel the push is for")
    pub: Optional[WsPublication] = None
    join: Optional[WsJoin] = None
    leave: Optional[WsLeave] = None
    unsubscribe: Optional[WsUnsubscribePush] = None
    message: Optional[WsMessage] = None
    subscribe: Optional[WsSubscribePush] = None
    connect: Optional[WsConnectPush] = None
    disconnect: Optional[WsDisconnect] = None
    refresh: Optional[WsRefreshPush] = None
    __properties: ClassVar[List[str]] = ["channel", "pub", "join", "leave", "unsubscribe", "message", "subscribe", "connect", "disconnect", "refresh"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WsPush from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of pub
        if self.pub:
            _dict['pub'] = self.pub.to_dict()
        # override the default output from pydantic by calling `to_dict()` of join
        if self.join:
            _dict['join'] = self.join.to_dict()
        # override the default output from pydantic by calling `to_dict()` of leave
        if self.leave:
            _dict['leave'] = self.leave.to_dict()
        # override the default output from pydantic by calling `to_dict()` of unsubscribe
        if self.unsubscribe:
            _dict['unsubscribe'] = self.unsubscribe.to_dict()
        # override the default output from pydantic by calling `to_dict()` of message
        if self.message:
            _dict['message'] = self.message.to_dict()
        # override the default output from pydantic by calling `to_dict()` of subscribe
        if self.subscribe:
            _dict['subscribe'] = self.subscribe.to_dict()
        # override the default output from pydantic by calling `to_dict()` of connect
        if self.connect:
            _dict['connect'] = self.connect.to_dict()
        # override the default output from pydantic by calling `to_dict()` of disconnect
        if self.disconnect:
            _dict['disconnect'] = self.disconnect.to_dict()
        # override the default output from pydantic by calling `to_dict()` of refresh
        if self.refresh:
            _dict['refresh'] = self.refresh.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WsPush from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "channel": obj.get("channel"),
            "pub": WsPublication.from_dict(obj["pub"]) if obj.get("pub") is not None else None,
            "join": WsJoin.from_dict(obj["join"]) if obj.get("join") is not None else None,
            "leave": WsLeave.from_dict(obj["leave"]) if obj.get("leave") is not None else None,
            "unsubscribe": WsUnsubscribePush.from_dict(obj["unsubscribe"]) if obj.get("unsubscribe") is not None else None,
            "message": WsMessage.from_dict(obj["message"]) if obj.get("message") is not None else None,
            "subscribe": WsSubscribePush.from_dict(obj["subscribe"]) if obj.get("subscribe") is not None else None,
            "connect": WsConnectPush.from_dict(obj["connect"]) if obj.get("connect") is not None else None,
            "disconnect": WsDisconnect.from_dict(obj["disconnect"]) if obj.get("disconnect") is not None else None,
            "refresh": WsRefreshPush.from_dict(obj["refresh"]) if obj.get("refresh") is not None else None
        })
        return _obj


